apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mlflow.name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- toYaml .Values.mlflow.storage.accessModes | nindent 4 }}
  storageClassName: {{ .Values.mlflow.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mlflow.storage.size }}
