apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mlflow.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.mlflow.name }}
spec:
  selector:
    app: {{ .Values.mlflow.name }}
  ports:
    - name: http
      port: {{ .Values.mlflow.service.port }}
      targetPort: http
      protocol: TCP
  type: {{ .Values.mlflow.service.type }}
