# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibana.fullname" . }}-config
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  kibana.yml: |
{{ tpl (.Files.Get "configs/kibana.yml") . | indent 4 }}
{{- end }}
